### ISSUE TITLE
Bug: Login: the submit button is hidden instead of disabled if the form can't be submitted

### ISSUE THREAD

**Issue by RichardWepnerTU** [do4gr/MeteorImageBoard#28]

**Comment by samirakotte** [comment]
Ich würde mal sagen, das das beabsichtigt ist. Also, du sollst dich ja eh nur anmelden können, wenn keines der Felder leer ist, oder?

**Comment by HannaHoJ** [comment]
Hmmm. Kommt drauf an, wie wir das Design vom login/sign in haben wollen.

Am 01.06.2017 14:58 schrieb "Zamrara" <notifications@github.com>:

**Comment by samirakotte** [comment]
genau, aber ein bug ist es jetzt halt nicht, denke ich.

**Comment by RichardWepnerTU** [comment]
"du sollst dich ja eh nur anmelden können, wenn keines der Felder leer ist, oder?": ja, aber das heißt nicht, dass der Button versteckt sein sollte. (Ich hatte vergessen dazuzuschreiben, dass er stattdessen nur deaktiviert sein sollte.)

**Comment by HannaHoJ** [comment]
fixed by taking richard crazy query
