### ISSUE TITLE
Bug: Navbar: The navbar doesn't adjust to all screen sizes

### ISSUE THREAD

**Issue by RichardWepnerTU** [do4gr/MeteorImageBoard#30]
Before the navbar adjusts to the smallest setting, the added buttons ("More Fun", user menu, "Logout") are cut off.

Suggestions:
- move the "Logout" button into the user menu
- hide and show some of the categories dynamically

**Comment by HannaHoJ** [comment]
navbar ajusts to screen size. reactstrap has a class 'navbar-toggleable' build in in the toggable props of nav. By taking 'toggable' out, you can substitute it with the bootstrap class 'navbar-toggable-*' whereas * is the scree size (lg, xl, md, sm, sx). For now i put it to 'navbar-toggleable-md'
