### ISSUE TITLE
Bug: Post Tag List: the users of the posts aren't requested

### ISSUE THREAD

**Issue by RichardWepnerTU** [do4gr/MeteorImageBoard#95]
The request for the post list for a tag doesn't seem to request the user informations of the posts authors. This causes the user to be displayed as "unknown user".

**Comment by HannaHoJ** [comment]
``<span className='author-tag'>
            		Author:
            		<Link to={`/myposts/`} className="profile-post-link">
               			{this.props.post.user ? this.props.post.user.name: "unknown user"}&nbsp;
           			</Link>
         		</span>``

if the username is not available it will tag the author as unknown user. This is only true for older posts.
