### ISSUE TITLE
Bug: List View: "unknown user"s are linked to a profile page

### ISSUE THREAD

**Issue by RichardWepnerTU** [do4gr/MeteorImageBoard#96]
If the user informations for a post author can't be retrieved, the text "unknown user" is displayed. This still links to a profile page (currently the visiting users profile, later probably an invalid page). If there is no user, there shouldn't be a link at all.

Further:
- there is no space between the label ("Author:") and the user name
- the link ends with a non-breaking space (an always visible space). The user can't have an empty username, so there will always be content within that element.

**Comment by HannaHoJ** [comment]
is artifical, when we didn't had authentication...we wont have unregistered users in the end.
